name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: 12
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      env:
        GRAPHENEDB_BRONZE_BOLT_URL: bolt://hobby-ogndcmahmnbggbkefcpdecbl.dbs.graphenedb.com:24786
        GRAPHENEDB_BRONZE_BOLT_USER: app112704712-avrTHz
        GRAPHENEDB_BRONZE_BOLT_PASSWORD: b.Zy6swi5jNfBb.nnVzFon7cuW4S4L4
      run: ./gradlew build -info
